# Generated by Django 5.2.3 on 2025-06-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
