

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json


{
    "username": "kingship",
    "password": "kingship"
}

#######

POST http://localhost:8000/blog/create/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4MjI1NDI2LCJpYXQiOjE3NTA0NDk0MjYsImp0aSI6IjA2MmQ0ZjM0NGU4YjQ5MDJiZTMzMzczNDIyMzYyMTAwIiwidXNlcl9pZCI6MX0.4RJG29qIa5sj1pGIvDrOqb8xK2ku2tABdM4M6jrUuvw

{
    "title": "title",
    "author": "author",
    "details": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt, neque? Ut consequatur et unde aut expedita magni necessitatibus id cumque, odio enim nulla distinctio, neque, voluptatem at tempora culpa eius."
}

###

GET http://localhost:8000/blog/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4MjI1NDI2LCJpYXQiOjE3NTA0NDk0MjYsImp0aSI6IjA2MmQ0ZjM0NGU4YjQ5MDJiZTMzMzczNDIyMzYyMTAwIiwidXNlcl9pZCI6MX0.4RJG29qIa5sj1pGIvDrOqb8xK2ku2tABdM4M6jrUuvw